name: Winter Collection Terraform Plan

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        working-directory: ./Terraform
        run: terraform init -upgrade

      - name: Terraform Validate
        working-directory: ./Terraform
        run: terraform validate

      - name: Terraform Format
        working-directory: ./Terraform
        run: terraform fmt -recursive

      - name: Terraform Plan
        working-directory: ./Terraform
        run: |
          terraform plan -input=false \
            -var="aws_account_id=${{ secrets.AWS_ACCOUNT_ID }}" \
            -var="aws_region=${{ secrets.AWS_REGION }}" \
            -var="image_tag=${{ secrets.IMAGE_TAG }}" \
            -var="repository_name=${{ secrets.ECR_REPOSITORY }}" \
            -var="domain_name=${{ secrets.DOMAIN_NAME }}"
 

     